### ISSUE TITLE
Has this project been redefined

### ISSUE THREAD

**Issue by java17lzh** [vsaint1/cs2-infestation#15]
Many previous functions have disappeared

**Comment by vsaint1** [comment]
yes, currently focusing **security** and **performance** over rushing new features, the project version 6.5 with kernel/usermode finished is available on this branch https://github.com/vsaint1/cs2-infestation/tree/discontinued

**Comment by java17lzh** [comment]
> 是的，目前将**安全性**和**性能**放在匆忙的新功能上，Kernel/Usermode Completed 的项目版本 6.5 在此分支[上可用 https://github.com/vsaint1/cs2-infestation/tree/discontinued](https://github.com/vsaint1/cs2-infestation/tree/discontinued)

Looking forward to your new version
