### ISSUE TITLE
How build and start this?

### ISSUE THREAD

**Issue by Verknot** [vsaint1/cs2-infestation#16]
![image](https://github.com/vsaint1/cs2-infestation/assets/62910245/6d9a70b1-112d-4010-9b54-2fe453d22051)
Where to find the driver and exe?

**Comment by vsaint1** [comment]
the project version 6.5 with kernel/usermode  done is available on this branch **https://github.com/vsaint1/cs2-infestation/tree/discontinued**

**Comment by Verknot** [comment]
I get BSOD(system_thread_exception_not_handled)  when i try to map the driver with kdmapper.

**Comment by vsaint1** [comment]
windows version?

**Comment by Verknot** [comment]
Win virsion 22H2 19045.3930
![image](https://github.com/vsaint1/cs2-infestation/assets/62910245/d34f7d56-dbc5-4f67-a9a8-ca2d570a8a98)

**Comment by vsaint1** [comment]
on code its correct but in driver config revert to **driver_entry**
![image](https://github.com/vsaint1/cs2-infestation/assets/69922096/3b1f9002-4c57-4cbd-906e-2149da9aceb6)

**Comment by Verknot** [comment]
I did as you said and now I'm getting a BSOD (system thread exception not handled)
