### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Enmton** [vsaint1/cs2-infestation#21]
C:\Users\****\Downloads\cs2-infestation-master\cs2-infestation-master>windows_build.bat --release
ERROR: Profile not found: C:\Users\****\.conan2\profiles\default
Das System kann den angegebenen Pfad nicht finden.
CMake Warning:
  Ignoring extra path from command line:

   ".."

CMake Error: The source directory "C:/Users/****/Downloads/cs2-infestation-master" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Error: could not load cache

**Comment by vsaint1** [comment]
run conan profile detect

**Comment by Enmton** [comment]
okay now it works :) 
but it close after 1-2 mins
and if i build driver this error comes

C:\Users\****\Downloads\cs2-infestation-master1\cs2-infestation-master\driver>if --release == --release (msbuild driver.sln /p:Configuration=Release /p:Platform="x64" )
Der Befehl "msbuild" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Users\****\Downloads\cs2-infestation-master1\cs2-infestation-master\driver>if --release == --debug (msbuild driver.sln /p:Configuration=Debug /p:Platform="x64" )

**Comment by vsaint1** [comment]
driver isnt ready yet, but need to use visual studio dev console to build. im debugging the release build randomly crashes

**Comment by ASSembler1337** [comment]
you can put all files in your own VS project, manually add all additionals and compile - profit!

**Comment by vsaint1** [comment]
thanks, fixed **release** build crashing due to read invalid **strings**
