### ISSUE TITLE
about web radar

### ISSUE THREAD

**Issue by dreambeaitbos** [vsaint1/cs2-infestation#23]
Can I use your project to implement the web radar function on KVM? What should I do if I can, thank you in advance for replying

**Comment by vsaint1** [comment]
ofc u can, must implement linux kvm read process memory, since im using conan as package manager all the libraries is build based on os/arch, and also remove all windows only related stuff.

**Comment by dreambeaitbos** [comment]
I encountered an error while compiling, why is this  
ERROR: The default build profile '/home/pdx/.conan2/profiles/default' doesn't exist.
You need to create a default profile (type 'conan profile detect' command)
or specify your own profile with '--profile:build=<myprofile>'
CMake Error at /usr/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:130 (message):
  Could not find toolchain file: build/generators/conan_toolchain.cmake
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

**Comment by vsaint1** [comment]
read the errors, answered too much about this **You need to create a default profile (type 'conan profile detect' command)
**

**Comment by vsaint1** [comment]
read the errors, answered too much about this You need to create a default profile (type 'conan profile detect' command)
