### ISSUE TITLE
Win 11 23H2 driver crashing

### ISSUE THREAD

**Issue by barkink12** [vsaint1/cs2-infestation#3]
Win 11 23H2 driver crashing when load with kdmapepr how can i fix ?

**Comment by vsaint1** [comment]
U need disable vulnerable drivers from loading

**Comment by barkink12** [comment]
![IMG_0099](https://github.com/vsaint1/cs2-infestation/assets/45940479/5187a9cb-daf1-4f5d-8288-52df97566b94)
kdmapper fixing stack cookies and k mode exception not handled bsod ?
