### ISSUE TITLE
kdmapper fixing stack cookie - bsod kmode_exception_not_handled

### ISSUE THREAD

**Issue by barkink12** [vsaint1/cs2-infestation#4]
kdmapper fixing stack cookie and bsod kmode_exception_not_handled vulnarable drivers already disabled
![krn](https://github.com/vsaint1/cs2-infestation/assets/45940479/6e71b4e0-be9c-40b2-ae5c-d91a6bfeb824)

**Comment by vsaint1** [comment]
thanks, i'll fix this soon, tested only win 10/11 < 22h2. but this is caused by the real driver entry point  **__security_init_cookie()**
