### ISSUE TITLE
hello, i have problem

### ISSUE THREAD

**Issue by eden13378** [vsaint1/cs2-infestation#5]
![Безымянный](https://github.com/vsaint1/cs2-infestation/assets/55891236/8c2bcdd0-7200-4aed-bb43-520c7a7a48cd)
win 10 21h2

**Comment by vsaint1** [comment]
translate to english pls

**Comment by eden13378** [comment]
unresolved external symbol driver_entry

**Comment by eden13378** [comment]
thx for fix <3
