### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by craxking** [vsaint1/cs2-infestation#7]
its giving me blue screen of death error when i try to map it with kdmapper
any fix?

**Comment by vsaint1** [comment]
thanks, tomorrow i'll push fix to github

![image](https://github.com/vsaint1/cs2-infestation/assets/69922096/b9687584-f2e3-4f4f-af43-77d42b5f008b)

**Comment by vsaint1** [comment]
fixed and pushed update, thanks!
