### ISSUE TITLE
error while building driver

### ISSUE THREAD

**Issue by slaxxer** [vsaint1/cs2-infestation#8]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MSB8040	Spectre-mitigated libraries are required for this project. Install them from the Visual Studio installer (Individual components tab) for any toolsets and architectures being used. Learn more: https://aka.ms/Ofhn4c	km-mouse	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets	504

which libs do i need to install?

**Comment by vsaint1** [comment]
![dwa](https://github.com/vsaint1/cs2-infestation/assets/69922096/9c0e69f8-e63a-45cb-89ad-044de73fa253)
