### ISSUE TITLE
usermode insta crash

### ISSUE THREAD

**Issue by eden13378** [vsaint1/cs2-infestation#9]
https://github.com/vsaint1/cs2-infestation/assets/55891236/6ed47324-baad-473c-953e-e1b49d433b83

**Comment by eden13378** [comment]
debug version no crash

**Comment by craxking** [comment]
insta crash for me as well on both windows 10 and windows 11

**Comment by vsaint1** [comment]
going to look and fix asap

**Comment by vsaint1** [comment]
tested here with everything enabled and nothing, @craxking  @eden13378 can you run directly  from visual studio  and try to reproduce the bug? so i can look at the stack trace
![image](https://github.com/vsaint1/cs2-infestation/assets/69922096/1f7b0c0c-cfe6-4355-b80e-84b8cab112eb)

**Comment by eden13378** [comment]
> tested here with everything enabled and nothing, @craxking @eden13378 can you run directly from visual studio and try to reproduce the bug? so i can look at the stack trace ![image](https://private-user-images.githubusercontent.com/69922096/303938295-1f7b0c0c-cfe6-4355-b80e-84b8cab112eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MzA3MjAsIm5iZiI6MTcwNzczMDQyMCwicGF0aCI6Ii82OTkyMjA5Ni8zMDM5MzgyOTUtMWY3YjBjMGMtY2ZlNi00MzU1LWI4MGUtODRiOGNhYjExMmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA5MzM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MDE2Y2M5ODU1YjRhNDFkYzhlYWE1NTRiZjFiZGU4ZjcwNjMwMzk2YjNjNDdmYTJkZDQ1OWZjN2YzYzUxODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BVxw_7HciUdysCk9Qzw_PNKMNRSMAsN_peTP6YX5ntY)

I'll try tonight

**Comment by eden13378** [comment]
https://github.com/vsaint1/cs2-infestation/assets/55891236/647168ae-8369-4d70-bf29-fb02af78e4b6

**Comment by vsaint1** [comment]
i saw your files and they seems to be outdated, tried to reproduce same steps with 5.5 and 6.0 versions but nothing happens.

**Comment by craxking** [comment]
> i saw your files and they seems to be outdated, tried to reproduce same steps with 5.5 and 6.0 versions but nothing happens.

**i tried your new build and now none of the features are working no esp,no aimbot whatsoever
also when i try to map the driver 2nd time without restarting the pc it gives me bsod**

**Comment by craxking** [comment]
### i tried the new build after updating the offsets
**now nothing is working no esp no aimbot whatsoever
also when i try to map the driver 2nd time(without restarting the pc) it gives me bsod**

**Comment by vsaint1** [comment]
cs2 had and update, i tested today with new offsets and its working 

std::ptrdiff_t dwEntityList = 0x18B1FE8;
std::ptrdiff_t dwLocalPlayerPawn = 0x17272E8;
std::ptrdiff_t dwViewMatrix = 0x19112D0;
